apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-admin-secret
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: jenkins-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: jenkins-admin-user
      remoteRef:
        key: jenkins-admin-secret
        property: jenkins-admin-user
    - secretKey: jenkins-admin-password
      remoteRef:
        key: jenkins-admin-secret
        property: jenkins-admin-password