controller:
  componentName: jenkins-controller
  image: jenkins/jenkins
  tag: lts-jdk17
  installPlugins:
    - kubernetes:4269.vdfb_37c52b_8b_4
    - workflow-aggregator:596.v8c21c963d92d
    - git:5.2.2
    - configuration-as-code:1810.v9b_c30a_249a_4
    - blueocean:1.27.10
  resources:
    requests:
      cpu: "500m"
      memory: "1024Mi"
    limits:
      cpu: "2"
      memory: "4096Mi"
  javaOpts: "-Xms512m -Xmx2048m"
  serviceType: ClusterIP
  servicePort: 8080
  targetPort: 8080
  admin:
    existingSecret: jenkins-admin-secret # Use External Secrets Operator with AWS Secrets Manager
  JCasC:
    enabled: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Managed by ArgoCD via GitOps - Utility Cluster"
  probes:
    startupProbe:
      enabled: true
    livenessProbe:
      enabled: true
    readinessProbe:
      enabled: true
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: platform-tools
    hosts:
      - jenkins.platform.svc.cluster.local
    tls: [] # configure if you front with certs

persistence:
  enabled: true
  existingClaim: "" # or let it create
  storageClass: gp3
  size: 20Gi

agent:
  enabled: true
  image: jenkins/inbound-agent
  tag: latest
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
  # For dynamic Karpenter scaling
  podTemplates:
    - name: "dynamic-agent"
      label: "dynamic"
      nodeUsageMode: NORMAL
      containers:
        - name: "jnlp"
          image: "jenkins/inbound-agent:latest"
          args: "${computer.jnlpmac} ${computer.name}"
          resourceRequestCpu: "200m"
          resourceRequestMemory: "256Mi"
          resourceLimitCpu: "1"
          resourceLimitMemory: "512Mi"
      nodeSelector: {}
      tolerations: []