resources:
  - clusterissuer-letsencrypt-prod.yaml
  - clusterissuer-letsencrypt-staging.yaml
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.15.0
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml